name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build for multiple platforms
        run: |
          # Set version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Building version: $VERSION"
          
          # Update version in scripts
          sed -i "s/VERSION=\"0.0.1\"/VERSION=\"$VERSION\"/g" scripts/release.sh
          
          # Build for all platforms
          ./scripts/release.sh build
          
          # List built files
          ls -la dist/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            swagen-${{ github.ref_name }}.tar.gz
            dist/swagen-linux-amd64
            dist/swagen-linux-arm64
            dist/swagen-darwin-amd64
            dist/swagen-darwin-arm64
            dist/swagen-windows-amd64.exe
            dist/swagen-windows-arm64.exe
            dist/*.sha256
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/
          asset_name: swagen-${{ github.ref_name }}-binaries
          asset_content_type: application/octet-stream
